repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "974bb4de56a6f5da690a64709a864a7d554b7c14"
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/hakancelikdev/unimport
      rev: 59883a2d8805b533fb06fc28923f07bc1f377f4a
      hooks:
          - id: unimport
            args: [--remove, --include-star-import]
    - repo: https://github.com/pycqa/isort
      rev: "f82ecc96e0a6bbebdea4431d99aed8c9855e94ae"
      hooks:
          - id: isort
            files: "ehva/.*"
            args: ["--profile", "black", "--filter-files"]

    - repo: https://github.com/psf/black
      rev: "7f033136ac5e0e5bf6cf322dd60b4a92050eedc4"
      hooks:
          - id: black

    - repo: https://gitlab.com/pycqa/flake8
      rev: "21d3c70d676007470908d39b73f0521d39b3b997"
      hooks:
          - id: flake8

    - repo: https://github.com/kynan/nbstripout
      rev: 8cafdcc393232045208137698dbeb42d6e0dd9e8
      hooks:
          - id: nbstripout
            files: ".ipynb"

    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: ""
    #   hooks:
    #       - id: mypy
    #         exclude: ^(docs/|example-plugin/|tests/fixtures)
    # - repo: https://github.com/pycqa/pydocstyle
    #   rev: ""
    #   hooks:
    #       - id: pydocstyle
